Mentor profile form
somalisintech/mentorship-website pull request #85
Opened 2022-11-27 10:15 UTC by xbdirisxk

2022-11-27 10:28 UTC, abshirahmed requested changes

2022-11-27 10:28 UTC, abshirahmed commented on src/components/mentorForm/PersonalInformationForm.tsx
> +  const countries = ['Somalia', 'Somaliland', 'Ethiopia', 'Kenya', 'Djibouti'];
we probably want to extend the number of countries in the list and pull in this data from an external service.

2022-11-27 10:28 UTC, abshirahmed commented on src/pages/profile/index.tsx
> +  console.log('===>', auth.currentUser);
you may want to remove these until we implement some logic to handle the user logged in state.

2022-11-27 11:04 UTC, xbdirisxk commented on src/components/mentorForm/PersonalInformationForm.tsx
> +  const countries = ['Somalia', 'Somaliland', 'Ethiopia', 'Kenya', 'Djibouti'];
yes, I used this data as placeholder but real counties/regions must come from the backend

2022-11-27 16:53 UTC, abshirahmed commented on src/components/DropDown.tsx
> +          // eslint-disable-next-line react/jsx-key
can this be achieved without having to ignore eslint?

2022-11-28 06:02 UTC, xbdirisxk commented on src/components/DropDown.tsx
> +          // eslint-disable-next-line react/jsx-key
yup we can use the index of the element as key but for now we can leave it like that until the service is ready

2023-02-05 14:35 UTC, closed without merging